name: Get Upstream Version

on:
  push:
    branches:
      - main

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Upstream Version
        id: upstream-version
        uses: your-action-repo/get-upstream-version-action@v1

      - name: Display Upstream Version
        run: echo "Upstream version is ${{ steps.upstream-version.outputs.version }}"
